# Ändra localhost:4000 till er grupps basurl som ni fått.
@baseUrl=https://jau22-recept-grupp4-xzvarhmra742.reky.se

# Hämtar alla recept
GET {{baseUrl}}/recipes HTTP/1.1

###

# Lägger till ett nytt recept
POST {{baseUrl}}/recipes HTTP/1.1
Content-Type: application/json

{
    "title": "Toast skagen",
    "description": "Gott till champagne",
    "ratings": [],
    "imageUrl": "https://assets.icanet.se/e_sharpen:80,q_auto,dpr_1.25,w_718,h_718,c_lfill/imagevaultfiles/id_223427/cf_259/korvstroganoff_med_ris.jpg",
    "timeInMins": 15,
    "categories": [ "Förrätt", "Skaldjur", "Smaskigt" ],
    "instructions": [ "Stek brödet", "Lägg på röran", "Toppa med Dill"],
    "ingredients": [
        {
            "name": "Salt",
            "amount": 1,
            "unit": "tsk"
        },
        {
            "name": "Peppar",
            "amount": 1,
            "unit": "tsk"
        },
        {
            "name": "Smör",
            "amount": 100,
            "unit": "gram"
        }
    ]
}

###

# Lägger till ett nytt recept
POST {{baseUrl}}/recipes HTTP/1.1
Content-Type: application/json

{
    "title": "Bruscetta",
    "description": "Att börja med",
    "ratings": [2, 3, 4, 1, 2, 3],
    "imageUrl": "https://assets.icanet.se/e_sharpen:80,q_auto,dpr_1.25,w_718,h_718,c_lfill/imagevaultfiles/id_223427/cf_259/korvstroganoff_med_ris.jpg",
    "timeInMins": 15,
    "categories": [ "Förrätt", "Italienskt" ],
    "instructions": [ "Stek brödet", "Hacka tomater och Mozarella", "Lägg på brödet"],
    "ingredients": [
        {
            "name": "Bröd",
            "amount": 1,
            "unit": "skiva"
        },
        {
            "name": "Tomat",
            "amount": 2,
            "unit": "stycken"
        }
    ]
}

###
# Söker bland alla recept
GET {{baseUrl}}/recipes?query=toas HTTP/1.1

###

# Hämtar ett enskilt recept
GET {{baseUrl}}/recipes/632d9fcb6e7766b37d9837f5 HTTP/1.1

###

# Tar bort ett recept
DELETE {{baseUrl}}/recipes/632d9fcb6e7766b37d9837f5 HTTP/1.1

###

# Uppdaterar ett recept
PATCH {{baseUrl}}/recipes/632d9fcb6e7766b37d9837f5 HTTP/1.1
Content-Type: application/json

{
  "description": "Gott till apelsinsaft"
}

###

# Hämtar alla kategorier
GET {{baseUrl}}/categories HTTP/1.1

###

# Hämtar alla recept i en viss kategori (Förrätt)
GET {{baseUrl}}/categories/Förrätt/recipes HTTP/1.1

###

# Söker bland recept i en viss kategori
GET {{baseUrl}}/categories/Förrätt/recipes?query=brus HTTP/1.1

###

# Lägger till ett omdöme (1-5) för ett recept
POST {{baseUrl}}/recipes/632da30c6e7766b37d983811/ratings
Content-Type: application/json

{
    "rating": 1
}
###

# Hämtar alla kommentarer för ett recept
GET {{baseUrl}}/recipes/632da30c6e7766b37d983811/comments

###

# Lägger till en kommentar för ett recept
POST {{baseUrl}}/recipes/632da30c6e7766b37d983811/comments
Content-Type: application/json

{
    "comment": "För mycket salt!",
    "name": "Bosse"
}

###

# Tömmer all data i api:et
GET {{baseUrl}}/clear HTTP/1.1

###
